export const USER_LOGIN_SUCCESS = "USER_LOGIN_SUCCESS"
export const USER_LOGIN_FAIL = "USER_LOGIN_FAIL"
export const USER_LOGOUT = "USER_LOGOUT"

export const UI_START_LOADING = "UI_START_LOADING"
export const UI_STOP_LOADING = "UI_STOP_LOADING"

export const UPDATE_DATA = "UPDATE_DATA"
export const UPDATE_QUERY_DATA = "UPDATE_QUERY_DATA"
export const UPDATE_ON_BOARD_COUNT = "UPDATE_ON_BOARD_COUNT"
export const INIT_FETCH_DATA = "INIT_FETCH_DATA"
